### ISSUE TITLE
Where are the older sheets?

### ISSUE THREAD

**Issue by David-Zhang-test** [AnotiaWang/animenz#2]
Hello! I'm a fan of Animenz also a fan of piano and anime.
I have been using your website since 2 years ago, but I noticed it had changed recently. I remembered that there were some older sheets and a zip contained all sheets of animenz that had been published on sheethost. Now, some of them gone and some new ones were uploaded. Is this a misoperation that some old sheets were covered by new ones? And could you please reupload old sheets?
Thank you very much!

**Comment by David-Zhang-test** [comment]
不好意思，发现您应该是主要使用中文，用中文交流会更方便
我2年前就在使用你搭建的网站，但最近网站进行了改版。我记得原先有一些老谱子和Animenz发布在sheethost上的全集（大概18年以前的），现在有一些新谱子上传，最老的谱子是京紫的WILL，再之前的谱子无法看到和下载了。请问您是误操作使得原有谱子被覆盖了吗（所有谱子的tag都是22.11.26，有一些老谱子比如21年的也被打上22年的tag）希望您能重新上传之前的谱子，谢谢！

**Comment by AnotiaWang** [comment]
是的，我之前误操作，把一些源文件删除了，只能从头弄一遍。刚加上了合集：https://animenz.ataw.top/posts/old-sheets-collection

你说的 tag 其实是发布日期，那个是我开始恢复网站的日子

**Comment by David-Zhang-test** [comment]
Roger.
感谢你为这个网站的努力！
我还有一篇非官方谱，会通过邮箱发给您

**Comment by kanition** [comment]
@AnotiaWang 赞美无私大佬，感谢分享！！！

**Comment by sclsj** [comment]
下载链接提示“分享不存在或已过期“
